#!/bin/bash

EMACS_DIR=${EMACS_DIR:-~/.emacs.d}
FILES="init.*"

# Check if directory exists
if [ ! -d "$EMACS_DIR" ]; then
  echo "Directory $EMACS_DIR does not exist"
  read -p "Create directory? (y/n): " response
  if [ "$response" = "y" ]; then
    mkdir -p "$EMACS_DIR"
  else
    echo "Aborting script"
    exit 1
  fi
fi

for file in $FILES; do
    if [ -f "$file" ]; then
        ln -si "$(pwd)/$file" "$EMACS_DIR/$file"
    fi
done
